spring:
  profiles:
    active: native
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/${server.port}

server:
  port: 8761
